// <auto-generated />
using MVCCRUD.DataAcces;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MVCCRUD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MVCCRUD.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("product_name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Choy",
                            Price = 500m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Qurut",
                            Price = 600m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shaftoli",
                            Price = 700m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Daftar",
                            Price = 900m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Qulupnay",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kundalik",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Zaryadchik",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kefir",
                            Price = 1300m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Moloko",
                            Price = 1400m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Olma",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Guruch",
                            Price = 1600m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bolalar kiyimi",
                            Price = 1700m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bosma",
                            Price = 1800m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Non",
                            Price = 1900m
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sabzi",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Gilos",
                            Price = 2100m
                        },
                        new
                        {
                            Id = 17,
                            Name = "Sut",
                            Price = 2200m
                        },
                        new
                        {
                            Id = 18,
                            Name = "Dorixona yopiq yog'i",
                            Price = 2300m
                        },
                        new
                        {
                            Id = 19,
                            Name = "Planshet",
                            Price = 2400m
                        },
                        new
                        {
                            Id = 20,
                            Name = "Telefon",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 21,
                            Name = "Oshxona mebellari",
                            Price = 2600m
                        },
                        new
                        {
                            Id = 22,
                            Name = "Buxanka",
                            Price = 2700m
                        },
                        new
                        {
                            Id = 23,
                            Name = "Kofe",
                            Price = 2800m
                        },
                        new
                        {
                            Id = 24,
                            Name = "Pishiriqlar",
                            Price = 2900m
                        },
                        new
                        {
                            Id = 25,
                            Name = "Ruchka",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 26,
                            Name = "Yengil telli choy",
                            Price = 3100m
                        },
                        new
                        {
                            Id = 27,
                            Name = "Shokolad",
                            Price = 3200m
                        },
                        new
                        {
                            Id = 28,
                            Name = "Plenka",
                            Price = 3300m
                        },
                        new
                        {
                            Id = 29,
                            Name = "Komp'yuter",
                            Price = 3400m
                        },
                        new
                        {
                            Id = 30,
                            Name = "Paltar",
                            Price = 3500m
                        },
                        new
                        {
                            Id = 31,
                            Name = "Disk",
                            Price = 3600m
                        },
                        new
                        {
                            Id = 32,
                            Name = "Uchqun",
                            Price = 3700m
                        },
                        new
                        {
                            Id = 33,
                            Name = "Konditsioner",
                            Price = 3800m
                        },
                        new
                        {
                            Id = 34,
                            Name = "Shampun",
                            Price = 3900m
                        },
                        new
                        {
                            Id = 35,
                            Name = "Avtomobil",
                            Price = 4000m
                        },
                        new
                        {
                            Id = 36,
                            Name = "Ovqat",
                            Price = 4100m
                        },
                        new
                        {
                            Id = 37,
                            Name = "Qush",
                            Price = 4200m
                        },
                        new
                        {
                            Id = 38,
                            Name = "Muzlatkich",
                            Price = 4300m
                        },
                        new
                        {
                            Id = 39,
                            Name = "Tarvuz",
                            Price = 4400m
                        },
                        new
                        {
                            Id = 40,
                            Name = "Mayka",
                            Price = 4500m
                        },
                        new
                        {
                            Id = 41,
                            Name = "Mevalar",
                            Price = 4600m
                        },
                        new
                        {
                            Id = 42,
                            Name = "Kapusta",
                            Price = 4700m
                        },
                        new
                        {
                            Id = 43,
                            Name = "Oshpaz",
                            Price = 4800m
                        },
                        new
                        {
                            Id = 44,
                            Name = "Pitsa",
                            Price = 4900m
                        },
                        new
                        {
                            Id = 45,
                            Name = "Yog'och",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 46,
                            Name = "Futbolka",
                            Price = 5100m
                        },
                        new
                        {
                            Id = 47,
                            Name = "Shlyapa",
                            Price = 5200m
                        },
                        new
                        {
                            Id = 48,
                            Name = "Mushak",
                            Price = 5300m
                        },
                        new
                        {
                            Id = 49,
                            Name = "Tovuq",
                            Price = 5400m
                        },
                        new
                        {
                            Id = 50,
                            Name = "Moyinka",
                            Price = 5500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
